[package]
name = "pong_with_rust"
version = "0.1.0"
authors = ["Victor <victor.as.nascimento@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"
rand = "0.8.1"
